version: '3.8'

services:
  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=1000'
    container_name: morefixes_db
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./dump_morefixes_27-03-2024_19_52_58.sql:/docker-entrypoint-initdb.d/dump_morefixes_27-03-2024_19_52_58.sql

volumes:
  postgres_data2:
